[[Races]]
    ID="1001"               #赛事ID
    EnterTime=""          #比赛几点开始
    Desc="新人快速赛A"     #比赛描述
    EnterFee=0.1          #报名费
    ConDes="满三人开赛"     #满三人开赛
    Match=1             #是否为随机匹配场(1表示满足三人即可开赛,2表示比赛到点满足多少人条件即可开赛抉择出前几名获取奖励)
    MatchType="海选赛"            #赛事类型
    AwardDesc="前一名有奖励"
    AwardTitle=["第一名"]
    AwardContent=["1元"]
    Award=1.0
    RoundNum="2局1副"
    Round=2
    BaseScore=1 #基础分数
    LimitPlayer=3 #最低几人开赛

[[Races]]
    ID="1002"               #赛事ID
    EnterTime=""          #比赛几点开始
    Desc="新人快速赛B"     #比赛描述
    EnterFee=0.2          #报名费
    ConDes="满三人开赛"     #满三人开赛
    Match=1             #是否为随机匹配场(1表示满足三人即可开赛,2表示比赛到点满足多少人条件即可开赛抉择出前几名获取奖励)
    MatchType="海选赛"            #赛事类型
    AwardDesc="前一名有奖励"
    AwardTitle=["第一名"]
    AwardContent=["1元"]
    Award=1.0
    RoundNum="3局1副"
    Round=3
    BaseScore=1 #基础分数
    LimitPlayer=3 #最低几人开赛

[[Races]]
    ID="1003"               #赛事ID
    EnterTime=""          #比赛几点开始
    Desc="10点券快速赛"     #比赛描述
    EnterFee=1.0          #报名费
    ConDes="满三人开赛"     #满三人开赛
    Match=1             #是否为随机匹配场(1表示满足三人即可开赛,2表示比赛到点满足多少人条件即可开赛抉择出前几名获取奖励)
    MatchType="海选赛"            #赛事类型
    AwardDesc="前一名有奖励"
    AwardTitle=["第一名"]
    AwardContent=["2.5元"]
    Award=2.5
    RoundNum="2局1副"
    Round=2
    BaseScore=1 #基础分数
    LimitPlayer=3 #最低几人开赛

[[Races]]
    ID="1004"               #赛事ID
    EnterTime=""          #比赛几点开始
    Desc="入门极速赛"     #比赛描述
    EnterFee=0.5          #报名费
    ConDes="满三人开赛"     #满三人开赛
    Match=1             #是否为随机匹配场(1表示满足三人即可开赛,2表示比赛到点满足多少人条件即可开赛抉择出前几名获取奖励)
    MatchType="海选赛"            #赛事类型
    AwardDesc="前一名有奖励"
    AwardTitle=["第一名"]
    AwardContent=["3.0元"]
    Award=3.0
    RoundNum="2局1副"
    Round=2
    BaseScore=1 #基础分数
    LimitPlayer=3 #最低几人开赛
